# note
* I won't try to generalize NN here. Just plow through this `400>25>10` setup

In [7]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

import sys
sys.path.append('..')

from helper import nn
from helper import logistic_regression as lr
import numpy as np

# prepare data

In [25]:
X_raw, y_raw = nn.load_data('ex4data1.mat', transpose=False)

In [26]:
X = np.insert(X_raw, 0, np.ones(X_raw.shape[0]), axis=1)

In [27]:
X.shape

(5000, 401)

***

In [28]:
y_raw

array([10, 10, 10, ...,  9,  9,  9], dtype=uint8)

In [41]:
y = nn.expand_y(y_raw)
y

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])

# load weight

In [32]:
t1, t2 = nn.load_weight('ex4weights.mat')

In [33]:
t1.shape, t2.shape

((25, 401), (10, 26))

# feed forward
> (400 + 1) -> (25 + 1) -> (10)

<img style="float: left;" src="../img/nn_model.png">

In [49]:
nn.feed_forward(X, t1, t2)  # 5000*10

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])